# Generated by Django 5.0.7 on 2025-10-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción del pedido, ej: Sandwich Milanesa Completo', max_length=255)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LISTO', 'Listo para retirar'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=15)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True)),
                ('notificado_caja', models.BooleanField(default=False, help_text='Indica si la caja ya fue notificada con la alarma')),
            ],
            options={
                'ordering': ['fecha_hora_creacion'],
            },
        ),
    ]
